" DO NOT EDIT THIS FILE
" $HOME/.vimrc

source $HOME/.vim/conf/plug.vimrc      " plugin loader
source $HOME/.vim/conf/general.vimrc   " general settings
source $HOME/.vim/conf/basic.vimrc     " basic settings
source $HOME/.vim/conf/themes.vimrc    " theme and color settings
source $HOME/.vim/conf/leader.vimrc    " leader key settings
source $HOME/.vim/conf/functions.vimrc " custom functions
source $HOME/.vim/conf/plugins.vimrc   " plugin specific settings
